CREATE TABLE IF NOT EXISTS trainees (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    iti_code TEXT,
    iti_name TEXT,
    district TEXT,
    roll_no TEXT,
    trainee_name TEXT,
    trade_name TEXT,
    trade_code TEXT,
    course_duration TEXT,
    session TEXT,
    year TEXT,
    mobile_no TEXT,
    result TEXT,
    apprenticeship TEXT,
    employment TEXT,
    self_employment TEXT,
    higher_education TEXT,
    other TEXT,
    remark TEXT
);
